

export const words4 = ['Area','Army','Baby','Back','Ball','Band','Bank','Base','Bill','Body','Book',
'Call','Card','Care','Case','Cash','City','Club','Cost','Date','Deal','Door','Duty','East',
'Edge','Face','Fact','Farm','Fear','File','Film','Fire','Firm','Fish','Food','Foot','Form',
'Fund','Game','Girl','Goal','Gold','Hair','Half','Hall','Hand','Head','Help','Hill','Home',
'Hope','Hour','Idea','Kind','King','Lack','Lady','Land','Life','Line','List','Look','Lord',
'Loss','Love','Mark','Mary','Mind','Miss','Move','Name','Need','News','Note','Page','Pain',
'Pair','Park','Part','Past','Path','Paul','Plan','Play','Post','Race','Rain','Rate','Rest',
'Rise','Risk','Road','Rock','Role','Room','Rule','Sale','Seat','Shop','Show','Side','Sign',
'Site','Size','Skin','Sort','Star','Step','Task','Team','Term','Test','Text','Time','Tour',
'Town','Tree','Turn','Type','Unit','User','View','Wall','Week','West','Wife','Will','Wind',
'Wine','Wood','Word','Work','Year','Feel','Hers','Many','Mine','Mine','Much','None','Nowt',
'Ours','Same','Self','Some','Such','That','Thee','Them','They','This','Thou','What','When',
'Whom','Your','Bear','Beat','Blow','Burn','Call','Care','Cast','Come','Cook','Cope','Cost',
'Dare','Deal','Deny','Draw','Drop','Earn','Face','Fail','Fall','Fear','Feel','Fill','Find',
'Form','Gain','Give','Grow','Hang','Hate','Have','Head','Hear','Help','Hide','Hold','Hope',
'Hurt','Join','Jump','Keep','Kill','Know','Land','Last','Lead','Lend','Lift','Like','Link',
'Live','Look','Lose','Love','Make','Mark','Meet','Mind','Miss','Move','Must','Name','Need',
'Note','Open','Pass','Pick','Plan','Play','Pray','Pull','Push','Read','Rely','Rest','Ride',
'Ring','Rise','Risk','Roll','Rule','Save','Seek','Seem','Sell','Send','Shed','Show','Shut',
'Sign','Sing','Slip','Sort','Stay','Step','Stop','Suit','Take','Talk','Tell','Tend','Test',
'Turn','Vary','View','Vote','Wait','Wake','Walk','Want','Warn','Wash','Wear','Will','Wish',
'Work','Back','Bare','Bass','Blue','Bold','Busy','Calm','Cold','Cool','Damp','Dark','Dead',
'Deaf','Dear','Deep','Dual','Dull','Dumb','Easy','Evil','Fair','Fast','Fine','Firm','Flat',
'Fond','Foul','Free','Full','Glad','Good','Grey','Grim','Half','Hard','Head','High','Holy',
'Huge','Just','Keen','Kind','Last','Late','Lazy','Like','Live','Lone','Long','Loud','Main',
'Male','Mass','Mean','Mere','Mild','Nazi','Near','Neat','Next','Nice','Okay','Only','Open',
'Oral','Pale','Past','Pink','Poor','Pure','Rare','Real','Rear','Rich','Rude','Safe','Same',
'Sick','Slim','Slow','Soft','Sole','Sore','Sure','Tall','Then','Thin','Tidy','Tiny','Tory',
'True','Ugly','Vain','Vast','Very','Vice','Warm','Wary','Weak','Wide','Wild','Wise','Zero',
'Both','Else','Ergo','Lest','Like','Once','Only','Plus','Save','Than','That','Then','Thou',
'Till','Unto','When','Some','Ably','Afar','Anew','Away','Back','Damn','Dead','Deep','Down',
'Duly','Easy','Else','Even','Ever','Fair','Fast','Flat','Full','Good','Half','Hard','Here',
'High','Home','Idly','Just','Late','Like','Live','Long','Loud','Much','Near','Nice','Okay',
'Once','Only','Over','Part','Past','Real','Slow','Solo','Soon','Sure','That','Then','This',
'Thus','Very','When','Wide','Amid','Anti','Apud','Atop','Bout','Come','Down','From','Gain',
'Into','Like','Near','Nigh','Onto','Over','Past','Post','Save','Than','Till','Unto','Upon',
'Vice','Whiz','With','Ahem','Ahoy','Alas','Amen','Bang','Fore','Gosh','Hell','Meow','Ouch',
'Phew','Poof','Pooh','Wham','Whoa','Yuck'];

export const words3 = ['Ace','Aid','Aim','Air','Ale','Arm','Art','Awl','Eel','Ear','Era','Ice','Ire','Ilk',
'Oak','Oat','Oil','Ore','Owl','Urn','Web','Cab','Dab','Jab','Tab','Dad','Fad','Lad','Mad','Bag','Gag',
'Hag','Lag','Mag','Rag','Tag','Pal','Ham','Jam','Ram','Ban','Can','Fan','Man','Pan','Tan','Bap','Cap',
'Lap','Pap','Rap','Sap','Tap','Yap','Bar','Car','Jar','Tar','War','Bat','Cat','Hat','Mat','Pat','Tat',
'Rat','Vat','Caw','Jaw','Law','Maw','Paw','Bay','Cay','Day','Hay','Ray','Pay','Way','Max','Tax','Pea',
'Sea','Tea','Bed','Leg','Peg','Bee','Lee','Tee','Gem','Bet','Jet','Net','Pet','Set','Den','Hen','Men',
'Pen','Ten','Yen','Dew','Mew','Pew','Bib','Fib','Jib','Rib','Bid','Kid','Lid','Tie','Lie','Pie','Fig',
'Jig','Pig','Rig','Wig','Dim','Bin','Din','Fin','Gin','Pin','Sin','Tin','Win','Dip','Lip','Pip','Sip',
'Tip','Git','Hit','Kit','Pit','Wit','Bod','Cod','God','Mod','Pod','Rod','Doe','Foe','Hoe','Roe','Toe',
'Bog','Cog','Dog','Fog','Hog','Jog','Log','Con','Son','Ton','Zoo','Cop','Hop','Mop','Pop','Top','Bot',
'Cot','Dot','Lot','Pot','Tot','Bow','Cow','Sow','Row','Box','Pox','Boy','Soy','Toy','Cub','Nub','Pub',
'Tub','Bug','Hug','Jug','Mug','Rug','Tug','Bum','Gum','Hum','Rum','Tum','Bun','Gun','Pun','Run','Sun',
'Cup','Pup','Cut','Gut','Hut','Nut','Rut','Egg','Ego','Elf','Elm','Emu','End','Era','Eve','Eye','Ink',
'Inn','Ion','Ivy','Lye','Dye','Rye','Gym','Her','His','Him','Our','You','She','Add','Are','Eat','Oar',
'Oil','Use','Nab','Jab','Bag','Lag','Nag','Rag','Sag','Tag','Wag','Jam','Ram','Tan','Cap','Lap','Nap',
'Rap','Sap','Tap','Yap','Mar','Has','Was','Pat','Lay','Pay','Say','Tax','See','Get','Let','Net','Met',
'Pet','Set','Wet','Mew','Sew','Lie','Tie','Bog','Jog','Boo','Coo','Moo','Bop','Hop','Lop','Mop','Pop',
'Top','Sop','Bow','Mow','Row','Tow','Dub','Rub','Lug','Tug','Hum','Sup','Buy','Jot','Rot','Nod','Hem',
'Wed','Fib','Jib','Rib','Did','Dig','Jig','Rig','Dip','Nip','Sip','Rip','Zip','Gin','Win','Bit','Hit',
'Sit','Pry','Try','Cry','All','Fab','Bad','Mad','Far','Fat','Raw','Lax','Gay','Big','Dim','Fit','Red',
'Wet','Old','New','Hot','Coy','Fun','Ill','Odd','Shy','Dry','Wry','And','But','Yet','For','Nor','The',
'Not','How','Too','Yet','Now','Off','Any','Out','Why','Hey','Wow','Aye']

export const words2 = ['of', 'to', 'in', 'it', 'is', 'be', 'as', 'at', 'so', 'we',
    'he', 'by', 'or', 'on', 'do', 'if', 'me', 'my', 'up', 'an', 'go', 'no', 'us', 'am']

export const sums3 = 
    ['112','123','134','145','156','167','178','189','213','224','235','246','257','268','279','281',
        '314','325','336','347','358','369','415','426','437','448','459','516','527','538','549',
        '617','628','639','718','729','819','101','202','303','404','505','606','707','808','909']