

export const words4 = ['area','army','baby','back','ball','band','bank','base','bill','body','book',
'call','card','care','case','cash','city','club','cost','date','deal','door','duty','east',
'edge','face','fact','farm','fear','file','film','fire','firm','fish','food','foot','form',
'fund','game','girl','goal','gold','hair','half','hall','hand','head','help','hill','home',
'hope','hour','idea','kind','king','lack','lady','land','life','line','list','look','lord',
'loss','love','mark','mary','mind','miss','move','name','need','news','note','page','pain',
'pair','park','part','past','path','paul','plan','play','post','race','rain','rate','rest',
'rise','risk','road','rock','role','room','rule','sale','seat','shop','show','side','sign',
'site','size','skin','sort','star','step','task','team','term','test','text','time','tour',
'town','tree','turn','type','unit','user','view','wall','week','west','wife','will','wind',
'wine','wood','word','work','year','feel','hers','many','mine','mine','much','none','nowt',
'ours','same','self','some','such','that','thee','them','they','this','thou','what','when',
'whom','your','bear','beat','blow','burn','call','care','cast','come','cook','cope','cost',
'dare','deal','deny','draw','drop','earn','face','fail','fall','fear','feel','fill','find',
'form','gain','give','grow','hang','hate','have','head','hear','help','hide','hold','hope',
'hurt','join','jump','keep','kill','know','land','last','lead','lend','lift','like','link',
'live','look','lose','love','make','mark','meet','mind','miss','move','must','name','need',
'note','open','pass','pick','plan','play','pray','pull','push','read','rely','rest','ride',
'ring','rise','risk','roll','rule','save','seek','seem','sell','send','shed','show','shut',
'sign','sing','slip','sort','stay','step','stop','suit','take','talk','tell','tend','test',
'turn','vary','view','vote','wait','wake','walk','want','warn','wash','wear','will','wish',
'work','back','bare','bass','blue','bold','busy','calm','cold','cool','damp','dark','dead',
'deaf','dear','deep','dual','dull','dumb','easy','evil','fair','fast','fine','firm','flat',
'fond','foul','free','full','glad','good','grey','grim','half','hard','head','high','holy',
'huge','just','keen','kind','last','late','lazy','like','live','lone','long','loud','main',
'male','mass','mean','mere','mild','nazi','near','neat','next','nice','okay','only','open',
'oral','pale','past','pink','poor','pure','rare','real','rear','rich','rude','safe','same',
'sick','slim','slow','soft','sole','sore','sure','tall','then','thin','tidy','tiny','tory',
'true','ugly','vain','vast','very','vice','warm','wary','weak','wide','wild','wise','zero',
'both','else','ergo','lest','like','once','only','plus','save','than','that','then','thou',
'till','unto','when','some','ably','afar','anew','away','back','damn','dead','deep','down',
'duly','easy','else','even','ever','fair','fast','flat','full','good','half','hard','here',
'high','home','idly','just','late','like','live','long','loud','much','near','nice','okay',
'once','only','over','part','past','real','slow','solo','soon','sure','that','then','this',
'thus','very','when','wide','amid','anti','apud','atop','bout','come','down','from','gain',
'into','like','near','nigh','onto','over','past','post','save','than','till','unto','upon',
'vice','whiz','with','ahem','ahoy','alas','amen','bang','fore','gosh','hell','meow','ouch',
'phew','poof','pooh','wham','whoa','yuck'];

export const words3 = ['ace','aid','aim','air','ale','arm','art','awl','eel','ear','era','ice','ire','ilk',
'oak','oat','oil','ore','owl','urn','web','cab','dab','jab','tab','dad','fad','lad','mad','bag','gag',
'hag','lag','mag','rag','tag','pal','ham','jam','ram','ban','can','fan','man','pan','tan','bap','cap',
'lap','pap','rap','sap','tap','yap','bar','car','jar','tar','war','bat','cat','hat','mat','pat','tat',
'rat','vat','caw','jaw','law','maw','paw','bay','cay','day','hay','ray','pay','way','max','tax','pea',
'sea','tea','bed','leg','peg','bee','lee','tee','gem','bet','jet','net','pet','set','den','hen','men',
'pen','ten','yen','dew','mew','pew','bib','fib','jib','rib','bid','kid','lid','tie','lie','pie','fig',
'jig','pig','rig','wig','dim','bin','din','fin','gin','pin','sin','tin','win','dip','lip','pip','sip',
'tip','git','hit','kit','pit','wit','bod','cod','god','mod','pod','rod','doe','foe','hoe','roe','toe',
'bog','cog','dog','fog','hog','jog','log','con','son','ton','zoo','cop','hop','mop','pop','top','bot',
'cot','dot','lot','pot','tot','bow','cow','sow','row','box','pox','boy','soy','toy','cub','nub','pub',
'tub','bug','hug','jug','mug','rug','tug','bum','gum','hum','rum','tum','bun','gun','pun','run','sun',
'cup','pup','cut','gut','hut','nut','rut','egg','ego','elf','elm','emu','end','era','eve','eye','ink',
'inn','ion','ivy','lye','dye','rye','gym','her','his','him','our','you','she','add','are','eat','oar',
'oil','use','nab','jab','bag','lag','nag','rag','sag','tag','wag','jam','ram','tan','cap','lap','nap',
'rap','sap','tap','yap','mar','has','was','pat','lay','pay','say','tax','see','get','let','net','met',
'pet','set','wet','mew','sew','lie','tie','bog','jog','boo','coo','moo','bop','hop','lop','mop','pop',
'top','sop','bow','mow','row','tow','dub','rub','lug','tug','hum','sup','buy','jot','rot','nod','hem',
'wed','fib','jib','rib','did','dig','jig','rig','dip','nip','sip','rip','zip','gin','win','bit','hit',
'sit','pry','try','cry','all','fab','bad','mad','far','fat','raw','lax','gay','big','dim','fit','red',
'wet','old','new','hot','coy','fun','ill','odd','shy','dry','wry','and','but','yet','for','nor','the',
'not','how','too','yet','now','off','any','out','why','hey','wow','aye']

export const words2 = ['of', 'to', 'in', 'it', 'is', 'be', 'as', 'at', 'so', 'we',
    'he', 'by', 'or', 'on', 'do', 'if', 'me', 'my', 'up', 'an', 'go', 'no', 'us', 'am']

export const sums3 = 
    ['112','123','134','145','156','167','178','189','213','224','235','246','257','268','279','281',
        '314','325','336','347','358','369','415','426','437','448','459','516','527','538','549',
        '617','628','639','718','729','819','101','202','303','404','505','606','707','808','909']